swapping names

diff --git a/utils/bin/janus b/utils/bin/janus
--- a/utils/bin/janus
+++ b/utils/bin/janus
@@ -1,6 +1,6 @@
 #!/bin/bash
-source $OYSTER_HOME/utils/sapautils.sh
-#echo $OYSTER_HOME
+source $JANUS_HOME/utils/janusutils.sh
+#echo $JANUS_HOME
 
 elementIn () {
   local e match="$1"
@@ -12,10 +12,10 @@ elementIn () {
 createModule(){
   if [ "$#" -ne 2 ]; then
     # shellcheck disable=SC1065
-    printf "\n > oyster create requires 2 parameters: stage, module_name \n"
+    printf "\n > janus create requires 2 parameters: stage, module_name \n"
   fi
 
-  MOD_LOC=$OYSTER_HOME/r_modules/$1/$2
+  MOD_LOC=$JANUS_HOME/r_modules/$1/$2
   mkdir $MOD_LOC
   cd $MOD_LOC;mkdir plays defaults tests files templates
   touch defaults/main.yml tests/main.yml janus_example_search.md
@@ -24,12 +24,12 @@ createModule(){
 
 
 if [ "$#" -lt 1 ]; then
-    echo "Usage: oyster [command] [parameters]"
+    echo "Usage: janus [command] [parameters]"
 	exit
 fi
 
 MODULE='x'
-OYSTER_HOME=/Users/dporter/projects/janus
+JANUS_HOME=/Users/dporter/projects/janus
 while (( "$#" )); do
   case "$1" in
     create|c)
@@ -42,16 +42,16 @@ while (( "$#" )); do
     * )
       COMMAND=$1
       ARGS="$@"
-      ARGS="$ARGS --home $OYSTER_HOME"
-      exp_dir_list=$(ls ${OYSTER_HOME}/experiments)
+      ARGS="$ARGS --home $JANUS_HOME"
+      exp_dir_list=$(ls ${JANUS_HOME}/experiments)
       exp_array=($(echo $exp_dir_list))
       if elementIn $COMMAND "${exp_array[@]}"; then
-        python3 $OYSTER_HOME/utils/bin/interactive_exp.py --name $COMMAND --home $OYSTER_HOME --home_user $USER || echo "failed to successfully complete oyster session"
-        echo "*** COMPLETED INTERACTIVE OYSTER SESSION *****"
+        python3 $JANUS_HOME/utils/bin/interactive_exp.py --name $COMMAND --home $JANUS_HOME --home_user $USER || echo "failed to successfully complete JANUS session"
+        echo "*** COMPLETED INTERACTIVE JANUS SESSION *****"
         exit
       fi
       #for non interactive commands
-      python3 $OYSTER_HOME/utils/bin/$COMMAND.py $ARGS || echo "> oyster $ARGS is not a valid command. Please be sure to follow API parameter rules"
+      python3 $JANUS_HOME/utils/bin/$COMMAND.py $ARGS || echo "> janus $ARGS is not a valid command. Please be sure to follow API parameter rules"
       shift "$#"
       ;;
 
