added foundation for UI/UX of project

diff --git a/utils/bin/oyster b/utils/bin/oyster
--- a/utils/bin/oyster
+++ b/utils/bin/oyster
@@ -2,6 +2,13 @@
 source $OYSTER_HOME/utils/sapautils.sh
 #echo $OYSTER_HOME
 
+elementIn () {
+  local e match="$1"
+  shift
+  for e; do [[ "$e" == "$match" ]] && return 0; done
+  return 1
+}
+
 createModule(){
   if [ "$#" -ne 2 ]; then
     # shellcheck disable=SC1065
@@ -22,7 +29,7 @@ if [ "$#" -lt 1 ]; then
 fi
 
 MODULE='x'
-
+OYSTER_HOME=/Users/dporter/projects/sapa
 while (( "$#" )); do
   case "$1" in
     create|c)
@@ -32,15 +39,22 @@ while (( "$#" )); do
       shift 3
       createModule $STAGE $MODULE
       ;;
+    * )
+      COMMAND=$1
+      ARGS="$@"
+      ARGS="$ARGS --home $OYSTER_HOME"
+      exp_dir_list=$(ls ${OYSTER_HOME}/experiments)
+      exp_array=($(echo $exp_dir_list))
+      if elementIn $COMMAND "${exp_array[@]}"; then
+        python3 $OYSTER_HOME/utils/bin/interactive_exp.py --name $COMMAND --home $OYSTER_HOME --home_user $USER || echo "failed to successfully complete oyster session"
+        echo "*** COMPLETED INTERACTIVE OYSTER SESSION *****"
+        exit
+      fi
+      #for non interactive commands
+      python3 $OYSTER_HOME/utils/bin/$COMMAND.py $ARGS || echo "> oyster $COMMAND $ARGS is not a valid command. Please be sure to follow API parameter rules"
+      shift "$#"
+      ;;
 
-    -*|--*=) # unsupported flags
-      echo "Error: Unsupported flag $1" >&2
-      exit 1
-      ;;
-    *) # preserve positional arguments
-      PARAMS="$PARAMS $1"
-      shift
-      ;;
   esac
 done
 
